version: '3.3'  # version of compose format

services:
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 5050:5050  # host:container
  # Add more services below

  addition-service:
    build: ./Addition  # path is relative to docker-compose.yml location
    hostname: addition-service
    ports:
      - 5051:5051  # host:container
    
  minus-service:
    build: ./Subtraction  # path is relative to docker-compose.yml location
    hostname: minus-service
    ports:
      - 5052:5052
  multiply-service:
    build: ./Multiplication  # path is relative to docker-compose.yml location
    hostname: multiplication-service
    ports:
      - 5053:5053
  division-service:
    build: ./Division  # path is relative to docker-compose.yml location
    hostname: division-service
    ports:
      - 5054:5054