version: '3.3'  # version of compose format

services:
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 5050:5050  # host:container
  # Add more services below

  add-service:
    build: ./Addition  # path is relative to docker-compose.yml location
    hostname: add-service
    ports:
      - 5051:5051  # host:container
  minus-service:
    build: ./Subtraction  # path is relative to docker-compose.yml location
    hostname: minus-service
    ports:
      - 5052:5052
  mul-service:
    build: ./Multiplication  # path is relative to docker-compose.yml location
    hostname: mul-service
    ports:
      - 5053:5053
  div-service:
    build: ./Division  # path is relative to docker-compose.yml location
    hostname: div-service
    ports:
      - 5054:5054
  gcd-service:
    build: ./Gcd  # path is relative to docker-compose.yml location
    hostname: gcd-service
    ports:
      - 5055:5055
  modulo-service:
    build: ./Modulo
    hostname: modulo-service
    ports:
      - 5056:5056
  lcm-service:
    build: ./Lcm
    hostname: lcm-service
    ports:
      - 5057:5057
  exp-service:
    build: ./Exponent
    hostname: exp-service
    ports:
      - 5058:5058
  gt-service:
    build: ./Greater
    hostname: gt-service
    ports:
      - 5061:5061
  lt-service:
    build: ./Lesser
    hostname: lt-service
    ports:
      - 5062:5062
  equal-service:
    build: ./Equal
    hostname: equal-service
    ports:
      - 5063:5063